application: expertstracking
version: 2-0-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: build/bundled/bower_components
  secure: always

- url: /images
  static_dir: build/bundled/images
  secure: always

- url: /src
  static_dir: build/bundled/src
  secure: always

- url: /service-worker.js
  static_files: build/bundled/service-worker.js
  upload: build/bundled/service-worker.js
  secure: always

- url: /manifest.json
  static_files: build/bundled/manifest.json
  upload: build/bundled/manifest.json
  secure: always

- url: /.*
  static_files: build/bundled/index.html
  upload: build/bundled/index.html
  secure: always

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?bower\.json
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?node_modules/.*
- ^(.*/)?tests/.*
- ^.*.md|markdown
- ^(.*/)?bower_components/.*